### PR TITLE
441 exclude tests

### LINKED ISSUE #441: nightly test ./modules/benchmark_global_mutual_information.ipynb
**Describe the bug**
```
Running ./modules/benchmark_global_mutual_information.ipynb
Checking PEP8 compliance...
Running notebook...

Executing:   0%|          | 0/23 [00:00<?, ?cell/s]
Executing:   4%|▍         | 1/23 [00:01<00:27,  1.23s/cell]
Executing:  17%|█▋        | 4/23 [00:15<01:15,  3.98s/cell]
Executing:  22%|██▏       | 5/23 [00:15<00:55,  3.07s/cell]
Traceback (most recent call last):
  File "/opt/conda/bin/papermill", line 8, in <module>
    sys.exit(papermill())
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/papermill/cli.py", line 250, in papermill
    execute_notebook(
  File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 122, in execute_notebook
    raise_for_execution_errors(nb, output_path)
  File "/opt/conda/lib/python3.8/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
    raise error
papermill.exceptions.PapermillExecutionError: 
---------------------------------------------------------------------------
Exception encountered at "In [2]":
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_9481/2631594062.py in <module>
----> 1 import ants
      2 import os
      3 import tempfile
      4 import torch
      5 import plotly.graph_objects as go

ModuleNotFoundError: No module named 'ants'
```

### PR DESCRIPTION
**Pull request by wyli**
Signed-off-by: Wenqi Li <wenqil@nvidia.com>

Fixes #441

### Description
exclude tests because installation requires compiling

### Status
**Ready**

### Checks

- [ ] Notebook runs automatically `./runner [-p <regex_pattern>]`

### CODE REVIEW

File: runner.sh [hunk 1]
```diff
@@ -57,7 +56,11 @@ doChecks=true
 doRun=true
 autofix=false
 failfast=false
-pattern="-and -name '*' -and ! -wholename '*federated_learning*' -and ! -wholename '*unetr_btcv*' -and ! -wholename '*profiling_camelyon*' -and ! -wholename '*profiling_train_base_nvtx*'"
+pattern="-and -name '*' -and ! -wholename '*federated_learning*'\
+ -and ! -wholename '*unetr_btcv*'\
+ -and ! -wholename '*profiling_camelyon*'\
+ -and ! -wholename '*profiling_train_base_nvtx*'\
+ -and ! -wholename '*benchmark_global_mutual_information*'"
```
Comment (Nic-Ma) [inline runner.sh:63]: Hi @wyli ,

Is there any nice way to maintain this `runner.sh` file?
I found that we always missed the regex in this file when adding a new notebook..
What do you think?

Thanks in advance.

**Review by Nic-Ma — APPROVED** [review]

File: runner.sh (hunk 1 above)
Comment (wyli) [reply runner.sh:63]: Hi @Nic-Ma, It's not that we forgot to update the file (I have included it in the original PR https://github.com/Project-MONAI/tutorials/pull/438). The root cause is that `pip install -q antspyx` doesn't work on Blossom, but this is not an important issue as we have the core codebase tests to cover it.

Comment (Nic-Ma) [reply runner.sh:63]: I see, thanks.
